# frozen_string_literal: true

# Pin npm packages by running ./bin/importmap

pin 'application', preload: true
pin '@hotwired/stimulus', to: 'stimulus.min.js', preload: true
pin '@hotwired/stimulus-loading', to: 'stimulus-loading.js', preload: true
pin_all_from 'app/javascript/controllers', under: 'controllers'
pin '@hotwired/turbo-rails', to: 'turbo.min.js', preload: true
pin 'bootstrap', to: 'bootstrap.min.js', preload: true
pin '@popperjs/core', to: 'popper.js', preload: true
pin "codemirror" # @6.0.2
pin "@codemirror/autocomplete", to: "@codemirror--autocomplete.js" # @6.20.3
pin "@codemirror/commands", to: "@codemirror--commands.js" # @6.11.0
pin "@codemirror/language", to: "@codemirror--language.js" # @6.12.4
pin "@codemirror/lint", to: "@codemirror--lint.js" # @6.9.7
pin "@codemirror/search", to: "@codemirror--search.js" # @6.7.1
pin "@codemirror/state", to: "@codemirror--state.js" # @6.7.1
pin "@codemirror/view", to: "@codemirror--view.js" # @6.43.9
pin "@lezer/common", to: "@lezer--common.js" # @1.5.2
pin "@lezer/highlight", to: "@lezer--highlight.js" # @1.2.3
pin "crelt" # @1.0.7
pin "style-mod" # @4.1.3
pin "w3c-keyname" # @2.2.8
pin "@hotwired/turbo-rails", to: "turbo.min.js", preload: true
pin "@codemirror/language-data", to: "@codemirror--language-data.js" # @6.5.2
pin "@codemirror/autocomplete", to: "@codemirror--autocomplete.js" # @6.20.3
pin "@codemirror/lang-cpp", to: "@codemirror--lang-cpp.js" # @6.0.3
pin "@codemirror/lang-css", to: "@codemirror--lang-css.js" # @6.3.1
pin "@codemirror/lang-html", to: "@codemirror--lang-html.js" # @6.4.12
pin "@codemirror/lang-java", to: "@codemirror--lang-java.js" # @6.0.2
pin "@codemirror/lang-javascript", to: "@codemirror--lang-javascript.js" # @6.2.5
pin "@codemirror/lang-json", to: "@codemirror--lang-json.js" # @6.0.2
pin "@codemirror/lang-markdown", to: "@codemirror--lang-markdown.js" # @6.5.2
pin "@codemirror/lang-php", to: "@codemirror--lang-php.js" # @6.0.2
pin "@codemirror/lang-python", to: "@codemirror--lang-python.js" # @6.2.1
pin "@codemirror/lang-rust", to: "@codemirror--lang-rust.js" # @6.0.2
pin "@codemirror/lang-sql", to: "@codemirror--lang-sql.js" # @6.10.0
pin "@codemirror/lang-wast", to: "@codemirror--lang-wast.js" # @6.0.2
pin "@codemirror/lang-xml", to: "@codemirror--lang-xml.js" # @6.1.0
pin "@codemirror/language", to: "@codemirror--language.js" # @6.12.4
pin "@codemirror/legacy-modes/mode/apl", to: "@codemirror--legacy-modes--mode--apl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/asciiarmor", to: "@codemirror--legacy-modes--mode--asciiarmor.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/asn1", to: "@codemirror--legacy-modes--mode--asn1.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/asterisk", to: "@codemirror--legacy-modes--mode--asterisk.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/brainfuck", to: "@codemirror--legacy-modes--mode--brainfuck.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/clike", to: "@codemirror--legacy-modes--mode--clike.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/clojure", to: "@codemirror--legacy-modes--mode--clojure.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/cmake", to: "@codemirror--legacy-modes--mode--cmake.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/cobol", to: "@codemirror--legacy-modes--mode--cobol.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/coffeescript", to: "@codemirror--legacy-modes--mode--coffeescript.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/commonlisp", to: "@codemirror--legacy-modes--mode--commonlisp.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/crystal", to: "@codemirror--legacy-modes--mode--crystal.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/css", to: "@codemirror--legacy-modes--mode--css.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/cypher", to: "@codemirror--legacy-modes--mode--cypher.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/d", to: "@codemirror--legacy-modes--mode--d.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/diff", to: "@codemirror--legacy-modes--mode--diff.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/dockerfile", to: "@codemirror--legacy-modes--mode--dockerfile.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/dtd", to: "@codemirror--legacy-modes--mode--dtd.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/dylan", to: "@codemirror--legacy-modes--mode--dylan.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/ebnf", to: "@codemirror--legacy-modes--mode--ebnf.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/ecl", to: "@codemirror--legacy-modes--mode--ecl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/eiffel", to: "@codemirror--legacy-modes--mode--eiffel.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/elm", to: "@codemirror--legacy-modes--mode--elm.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/erlang", to: "@codemirror--legacy-modes--mode--erlang.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/factor", to: "@codemirror--legacy-modes--mode--factor.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/fcl", to: "@codemirror--legacy-modes--mode--fcl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/forth", to: "@codemirror--legacy-modes--mode--forth.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/fortran", to: "@codemirror--legacy-modes--mode--fortran.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/gas", to: "@codemirror--legacy-modes--mode--gas.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/gherkin", to: "@codemirror--legacy-modes--mode--gherkin.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/go", to: "@codemirror--legacy-modes--mode--go.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/groovy", to: "@codemirror--legacy-modes--mode--groovy.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/haskell", to: "@codemirror--legacy-modes--mode--haskell.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/haxe", to: "@codemirror--legacy-modes--mode--haxe.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/http", to: "@codemirror--legacy-modes--mode--http.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/idl", to: "@codemirror--legacy-modes--mode--idl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/javascript", to: "@codemirror--legacy-modes--mode--javascript.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/jinja2", to: "@codemirror--legacy-modes--mode--jinja2.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/julia", to: "@codemirror--legacy-modes--mode--julia.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/livescript", to: "@codemirror--legacy-modes--mode--livescript.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/lua", to: "@codemirror--legacy-modes--mode--lua.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/mathematica", to: "@codemirror--legacy-modes--mode--mathematica.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/mbox", to: "@codemirror--legacy-modes--mode--mbox.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/mirc", to: "@codemirror--legacy-modes--mode--mirc.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/mllike", to: "@codemirror--legacy-modes--mode--mllike.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/modelica", to: "@codemirror--legacy-modes--mode--modelica.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/mscgen", to: "@codemirror--legacy-modes--mode--mscgen.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/mumps", to: "@codemirror--legacy-modes--mode--mumps.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/nginx", to: "@codemirror--legacy-modes--mode--nginx.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/nsis", to: "@codemirror--legacy-modes--mode--nsis.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/ntriples", to: "@codemirror--legacy-modes--mode--ntriples.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/octave", to: "@codemirror--legacy-modes--mode--octave.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/oz", to: "@codemirror--legacy-modes--mode--oz.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/pascal", to: "@codemirror--legacy-modes--mode--pascal.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/perl", to: "@codemirror--legacy-modes--mode--perl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/pig", to: "@codemirror--legacy-modes--mode--pig.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/powershell", to: "@codemirror--legacy-modes--mode--powershell.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/properties", to: "@codemirror--legacy-modes--mode--properties.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/protobuf", to: "@codemirror--legacy-modes--mode--protobuf.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/puppet", to: "@codemirror--legacy-modes--mode--puppet.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/python", to: "@codemirror--legacy-modes--mode--python.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/q", to: "@codemirror--legacy-modes--mode--q.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/r", to: "@codemirror--legacy-modes--mode--r.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/rpm", to: "@codemirror--legacy-modes--mode--rpm.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/ruby", to: "@codemirror--legacy-modes--mode--ruby.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/sas", to: "@codemirror--legacy-modes--mode--sas.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/sass", to: "@codemirror--legacy-modes--mode--sass.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/scheme", to: "@codemirror--legacy-modes--mode--scheme.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/shell", to: "@codemirror--legacy-modes--mode--shell.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/sieve", to: "@codemirror--legacy-modes--mode--sieve.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/smalltalk", to: "@codemirror--legacy-modes--mode--smalltalk.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/solr", to: "@codemirror--legacy-modes--mode--solr.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/sparql", to: "@codemirror--legacy-modes--mode--sparql.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/spreadsheet", to: "@codemirror--legacy-modes--mode--spreadsheet.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/sql", to: "@codemirror--legacy-modes--mode--sql.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/stex", to: "@codemirror--legacy-modes--mode--stex.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/stylus", to: "@codemirror--legacy-modes--mode--stylus.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/swift", to: "@codemirror--legacy-modes--mode--swift.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/tcl", to: "@codemirror--legacy-modes--mode--tcl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/textile", to: "@codemirror--legacy-modes--mode--textile.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/tiddlywiki", to: "@codemirror--legacy-modes--mode--tiddlywiki.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/tiki", to: "@codemirror--legacy-modes--mode--tiki.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/toml", to: "@codemirror--legacy-modes--mode--toml.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/troff", to: "@codemirror--legacy-modes--mode--troff.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/ttcn", to: "@codemirror--legacy-modes--mode--ttcn.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/ttcn-cfg", to: "@codemirror--legacy-modes--mode--ttcn-cfg.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/turtle", to: "@codemirror--legacy-modes--mode--turtle.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/vb", to: "@codemirror--legacy-modes--mode--vb.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/vbscript", to: "@codemirror--legacy-modes--mode--vbscript.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/velocity", to: "@codemirror--legacy-modes--mode--velocity.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/verilog", to: "@codemirror--legacy-modes--mode--verilog.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/vhdl", to: "@codemirror--legacy-modes--mode--vhdl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/webidl", to: "@codemirror--legacy-modes--mode--webidl.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/xquery", to: "@codemirror--legacy-modes--mode--xquery.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/yacas", to: "@codemirror--legacy-modes--mode--yacas.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/yaml", to: "@codemirror--legacy-modes--mode--yaml.js" # @6.5.3
pin "@codemirror/legacy-modes/mode/z80", to: "@codemirror--legacy-modes--mode--z80.js" # @6.5.3
pin "@codemirror/state", to: "@codemirror--state.js" # @6.7.1
pin "@codemirror/view", to: "@codemirror--view.js" # @6.43.9
pin "@lezer/common", to: "@lezer--common.js" # @1.5.2
pin "@lezer/cpp", to: "@lezer--cpp.js" # @1.1.6
pin "@lezer/css", to: "@lezer--css.js" # @1.3.6
pin "@lezer/highlight", to: "@lezer--highlight.js" # @1.2.3
pin "@lezer/html", to: "@lezer--html.js" # @1.3.13
pin "@lezer/java", to: "@lezer--java.js" # @1.1.3
pin "@lezer/javascript", to: "@lezer--javascript.js" # @1.5.4
pin "@lezer/json", to: "@lezer--json.js" # @1.0.3
pin "@lezer/lr", to: "@lezer--lr.js" # @1.4.10
pin "@lezer/markdown", to: "@lezer--markdown.js" # @1.7.2
pin "@lezer/php", to: "@lezer--php.js" # @1.0.5
pin "@lezer/python", to: "@lezer--python.js" # @1.1.19
pin "@lezer/rust", to: "@lezer--rust.js" # @1.0.2
pin "@lezer/xml", to: "@lezer--xml.js" # @1.0.6
pin "style-mod" # @4.1.3
pin "w3c-keyname" # @2.2.8
pin "@codemirror/theme-one-dark", to: "@codemirror--theme-one-dark.js" # @6.1.3
pin "@marijn/find-cluster-break", to: "@marijn--find-cluster-break.js" # @1.0.3
pin "@codemirror/lang-angular", to: "@codemirror--lang-angular.js" # @0.1.4
pin "@codemirror/lang-go", to: "@codemirror--lang-go.js" # @6.0.1
pin "@codemirror/lang-jinja", to: "@codemirror--lang-jinja.js" # @6.0.1
pin "@codemirror/lang-less", to: "@codemirror--lang-less.js" # @6.0.2
pin "@codemirror/lang-liquid", to: "@codemirror--lang-liquid.js" # @6.3.2
pin "@codemirror/lang-sass", to: "@codemirror--lang-sass.js" # @6.0.2
pin "@codemirror/lang-vue", to: "@codemirror--lang-vue.js" # @0.1.3
pin "@codemirror/lang-yaml", to: "@codemirror--lang-yaml.js" # @6.1.3
pin "@codemirror/legacy-modes/mode/pug", to: "@codemirror--legacy-modes--mode--pug.js" # @6.5.3
pin "@lezer/go", to: "@lezer--go.js" # @1.0.1
pin "@lezer/sass", to: "@lezer--sass.js" # @1.1.0
pin "@lezer/yaml", to: "@lezer--yaml.js" # @1.0.4
